services:
  db_image:
    build: ./db_image
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
    networks:
      default:
        aliases:
          - pg_cluster
  db_repl_image:
    build: ./db_repl_image
    container_name: ${DB_REPL_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_HOST=${DB_HOST}
    networks:
      default:
        aliases:
          - pg_cluster
  bot_image:
    build: ./bot_image
    container_name: tg_bot
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - postgres_version=${postgres_version}
    volumes:
      - pg_logs:/pg_logs:ro
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data:
  pg_logs: